title: "Sai Vikram Kattamanchi"
tagline: "QA Automation Engineer | SDET | API + UI + Kafka Testing"
description: "Karate DSL | Postman | Cypress | Pact | Jenkins | Allure | Kafka | FHIR"
url: "https://vikramsaix.github.io"
baseurl: "/vikram-qa-portfolio"

lang: en
remote_theme: cotes2020/jekyll-theme-chirpy

email: vikramksv95@gmail.com
github:
  username: vikramsaix
linkedin:
  username: sai-vikram95

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

