title: "Sai Vikram Kattamanchi | QA Automation Portfolio"
description: "Portfolio of a Software Test Engineer / SDET specializing in automation frameworks like Selenium, Karate, Cucumber, and ReadyAPI"
theme: jekyll-theme-cayman
show_downloads: false
google_analytics:
