# ==== Site Settings ====
title: "Sai Vikram Kattamanchi"
tagline: "QA Automation Engineer | SDET | Java + Selenium + Karate + Cucumber"
description: >-
  A curated portfolio of QA Automation projects using Selenium WebDriver, Karate, REST Assured, and Cucumber with Jenkins CI/CD.

url: "https://vikramsaix.github.io"
baseurl: "/vikram-qa-portfolio"

lang: "en"
timezone: "America/New_York"

# ==== Author ====
author:
  name: "Sai Vikram Kattamanchi"
  email: "vikramksv95@gmail.com"
  github: vikramsaix
  linkedin: sai-vikram95

# ==== Theme ====
remote_theme: "mmistakes/minimal-mistakes"

# ==== SEO and Social ====
github:
  username: vikramsaix

# ==== Plugins ====
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# ==== Markdown ====
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6

# ==== Pagination ====
paginate: 5
paginate_path: /page:num/

# ==== Exclude Files ====
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE

# ==== Build Defaults ====
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
